//! Hikari EFI Graphics Constants

pub const PIXEL_FORMAT_RGB: u32 = 0;
pub const PIXEL_FORMAT_BGR: u32 = 1;
pub const PIXEL_FORMAT_BITMASK: u32 = 2;
pub const PIXEL_FORMAT_BLT_ONLY: u32 = 3;

pub const BLT_OPERATION_VIDEO_FILL: u32 = 0;
pub const BLT_OPERATION_VIDEO_TO_BUFFER: u32 = 1;
pub const BLT_OPERATION_BUFFER_TO_VIDEO: u32 = 2;
pub const BLT_OPERATION_VIDEO_TO_VIDEO: u32 = 3;

pub const GRAPHICS_OUTPUT_PROTOCOL_REVISION: u32 = 0x00010000;
