//! Hikari EFI Device Location Constants

pub const DEVICE_LOCATION_TYPE_HARDWARE: u8 = 0x01;
pub const DEVICE_LOCATION_TYPE_ACPI: u8 = 0x02;
pub const DEVICE_LOCATION_TYPE_MESSAGING: u8 = 0x03;
pub const DEVICE_LOCATION_TYPE_MEDIA: u8 = 0x04;
pub const DEVICE_LOCATION_TYPE_BIOS_BOOT: u8 = 0x05;
pub const DEVICE_LOCATION_TYPE_END: u8 = 0x7F;

pub const DEVICE_LOCATION_SUB_TYPE_END_ENTIRE: u8 = 0xFF;
pub const DEVICE_LOCATION_SUB_TYPE_END_INSTANCE: u8 = 0x01;

pub const DEVICE_LOCATION_SUB_TYPE_HARD_DRIVE: u8 = 0x01;
pub const DEVICE_LOCATION_SUB_TYPE_CDROM: u8 = 0x02;
pub const DEVICE_LOCATION_SUB_TYPE_VENDOR: u8 = 0x03;
pub const DEVICE_LOCATION_SUB_TYPE_UNIT_LOCATION: u8 = 0x04;
pub const DEVICE_LOCATION_SUB_TYPE_MEDIA_PROTOCOL: u8 = 0x05;
pub const DEVICE_LOCATION_SUB_TYPE_PIWG_FIRMWARE_UNIT: u8 = 0x06;
pub const DEVICE_LOCATION_SUB_TYPE_PIWG_FIRMWARE_VOLUME: u8 = 0x07;
pub const DEVICE_LOCATION_SUB_TYPE_RELATIVE_OFFSET_RANGE: u8 = 0x08;
pub const DEVICE_LOCATION_SUB_TYPE_RAM_DISK: u8 = 0x09;

pub const PARTITION_FORMAT_MBR: u8 = 0x01;
pub const PARTITION_FORMAT_GPT: u8 = 0x02;

pub const SIGNATURE_TYPE_NONE: u8 = 0x00;
pub const SIGNATURE_TYPE_MBR: u8 = 0x01;
pub const SIGNATURE_TYPE_GUID: u8 = 0x02;
