//! Memory Protection Flag Constants

pub const PROTECTION_READ: u8 = 0x01;
pub const PROTECTION_WRITE: u8 = 0x02;
pub const PROTECTION_EXECUTE: u8 = 0x04;
pub const PROTECTION_USER: u8 = 0x08;

pub const PROTECTION_KERNEL_READ_ONLY: u8 = PROTECTION_READ;
pub const PROTECTION_KERNEL_READ_WRITE: u8 = PROTECTION_READ | PROTECTION_WRITE;
pub const PROTECTION_KERNEL_EXECUTE: u8 = PROTECTION_READ | PROTECTION_EXECUTE;
pub const PROTECTION_USER_READ_ONLY: u8 = PROTECTION_READ | PROTECTION_USER;
pub const PROTECTION_USER_READ_WRITE: u8 = PROTECTION_READ | PROTECTION_WRITE | PROTECTION_USER;
pub const PROTECTION_USER_EXECUTE: u8 = PROTECTION_READ | PROTECTION_EXECUTE | PROTECTION_USER;
