//! Paging Flag Constants

pub const PRESENT: u64 = 1 << 0;
pub const WRITABLE: u64 = 1 << 1;
pub const USER_ACCESSIBLE: u64 = 1 << 2;
pub const WRITE_THROUGH: u64 = 1 << 3;
pub const CACHE_DISABLED: u64 = 1 << 4;
pub const ACCESSED: u64 = 1 << 5;
pub const DIRTY: u64 = 1 << 6;
pub const HUGE_PAGE: u64 = 1 << 7;
pub const GLOBAL: u64 = 1 << 8;
pub const NO_EXECUTE: u64 = 1 << 63;

pub const KERNEL_READ_ONLY: u64 = PRESENT | GLOBAL;
pub const KERNEL_READ_WRITE: u64 = PRESENT | WRITABLE | GLOBAL;
pub const KERNEL_EXECUTE: u64 = PRESENT | GLOBAL;
pub const KERNEL_READ_WRITE_NO_EXECUTE: u64 = PRESENT | WRITABLE | GLOBAL | NO_EXECUTE;

pub const USER_READ_ONLY: u64 = PRESENT | USER_ACCESSIBLE;
pub const USER_READ_WRITE: u64 = PRESENT | WRITABLE | USER_ACCESSIBLE;
pub const USER_EXECUTE: u64 = PRESENT | USER_ACCESSIBLE;
pub const USER_READ_WRITE_NO_EXECUTE: u64 = PRESENT | WRITABLE | USER_ACCESSIBLE | NO_EXECUTE;

pub const TABLE_FLAGS: u64 = PRESENT | WRITABLE | USER_ACCESSIBLE;
pub const KERNEL_TABLE_FLAGS: u64 = PRESENT | WRITABLE;

pub const MMIO_FLAGS: u64 = PRESENT | WRITABLE | CACHE_DISABLED | NO_EXECUTE;
